### PR TITLE
Fix sshd AuthorizedKeysCommand setting problem

### PR DESCRIPTION
**Pull request by maxgio92**
It seems that sshd's AuthorizedKeysCommand setting install did
not work on Debian-based distributions, since these directives:
- AuthorizedKeysCommand
- AuthorizedKeysCommandUser

are not present by default in sshd_config and the sed substitutions
did not work.
New checks are implemented in order to substitute or add corrected
lines of sshd configuration.

### CODE REVIEW

**Comment by michaelwittig** [comment]
is this related to #70 ?

**Comment by maxgio92** [comment]
Yes

**Comment by maxgio92** [comment]
Hi,
did you check this fix?
Thanks

**Comment by michaelwittig** [comment]
It seems that there are other issues as well with Ubuntu (see #72 ). I'm not using Ubuntu and looking for someone who can fix all Ubuntu issues and also create a automated test to make sure that it always will work (as simple as this: https://github.com/widdix/aws-ec2-ssh/blob/master/test/src/test/java/de/widdix/awsec2ssh/TestShowcase.java)

**Comment by maxgio92** [comment]
Hi @michaelwittig ,
thank you.
Anyway, If it can be useful to you, this bugfix is not only for Ubuntu but for Debian-based distributions.

**Comment by michaelwittig** [comment]
Hi @maxgio92 I created an ubuntu branch for all the ubuntu (Debian-based) related changes. I also modified the showcase to work with ubuntu to let us test the solution.
I will merge your PR into the ubuntu branch.

**Comment by maxgio92** [comment]
Thanks @michaelwittig

**Comment by michaelwittig** [comment]
We have several other issues with ubuntu: https://github.com/widdix/aws-ec2-ssh/issues?q=is%3Aissue+is%3Aopen+label%3Aubuntu

I don't have time and motivation to investigate them. If someone wants to pick them I'm happy!

**Comment by maxgio92** [comment]
Hi @michaelwittig ,
please see my new updates on my fork.
I fixed a problem and I added sshd service name switch based on RHEL-based or Debian-based distributions.
They could be added to your ubuntu branch.

**Pull request merged**
