### PR TITLE
Installer that works straight from Github, and an IAM policy snippet

### PR DESCRIPTION
**Pull request by uberbrady**
Rationale
---------
Not everyone can use CloudFormation, or necessarily would be able to integrate these CloudFormation scripts/examples in with their own CloudFormation setup.

So instead I've created a simple `install.sh` script that will download, configure, and execute these scripts. You could put it in your `user-data` to enable newly-launched systems to authenticate using IAM users, or potentially script it using Puppet or Chef.

Additionally, I created a JSON snippet which contains the minimal required policies to be able to let these scripts to run on one of your instances. Just create this policy script in IAM, and add it to any Role you want to assign to your newly-launched instances.

### CODE REVIEW

**Comment by michaelwittig** [comment]
Hi @uberbrady 
I like the idea! do you have time to add a few lines to the README.md? just as simple as saying that there is an installer :) 
Thanks
Michael

**Comment by uberbrady** [comment]
Will, and will mention the JSON snippet for the IAM policy.

**Comment by uberbrady** [comment]
Okay - added some schpiel to the README - also labeled your showcase as "CloudFormation" and the generic install as "non-CloudFormation."

Happy to make any additional edits for grammar or content, too. Getting ready to roll this out to some production servers.

**Comment by michaelwittig** [comment]
thanks @uberbrady

**Pull request merged**
